# SOLARIZED  HEX      XTERM  sRGB
# ---------  -------  -----  -----------
# base03     #002b36  234      0  43  54
# base02     #073642  235      7  54  66
# base01     #586e75  240     88 110 117
# base00     #657b83  241    101 123 131
# base0      #839496  244    131 148 150
# base1      #93a1a1  245    147 161 161
# base2      #eee8d5  254    238 232 213
# base3      #fdf6e3  230    253 246 227
# yellow     #b58900  136    181 137   0
# orange     #cb4b16  166    203  75  22
# red        #dc322f  160    220  50  47
# magenta    #d33682  125    211  54 130
# violet     #6c71c4   61    108 113 196
# blue       #268bd2   33     38 139 210
# cyan       #2aa198   37     42 161 152
# green      #859900   64    133 153   0

user:
  #268bd2
  - 38
  - 139
  - 210
group:
  #2aa198
  - 42
  - 161
  - 152
permission:
  read: dark_green
  write: dark_yellow
  exec: dark_red
  exec-sticky: 5
  no-access: 245
  octal: 6
  acl: dark_cyan
  context: cyan
date:
  hour-old:
    #073642
    - 7
    - 54
    - 66
  day-old:
    #657b83
    - 101
    - 123
    - 131
  older:
    #93a1a1
    - 147
    - 161
    - 161
size:
  none: 245
  small: 136
  medium: 166
  large: 160
inode:
  valid:
    #d33682
    - 211
    - 54
    - 120
  invalid: 245
links:
  valid:
    #d33682
    - 211
    - 54
    - 120
  invalid: 245
tree-edge: 245
